import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nonton Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="p-4 flex gap-12 items-center font-bold">
            <ModeToggle />
            <Link href="/videos" className="bg-slate-200 p-2 rounded-md dark:text-green-400 text-yellow-400">
              Nonton Project
            </Link>
          </div>
          <div className="p-4">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
